In [12]:
!pip install pandas
import pandas as pd

# Load the uploaded movie dataset
file_path = 'movies.csv'
movies_df = pd.read_csv(file_path)


# Display the first few rows of the dataset to understand its structure
movies_df.head()

Requirement already satisfied: pandas in ./.venv/lib/python3.11/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in ./.venv/lib/python3.11/site-packages (from pandas) (2.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.11/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.11/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0

In [13]:
# Function to generate a prompt for a movie
def generate_prompt(row):
    return f"Tell me about the movie {row['name']} released in {row['year']}. It is a {row['genre']} directed by {row['director']} and stars {row['star']}. What are some notable aspects of this movie?"

# Apply the function to each row in the dataframe to create a new column for prompts
movies_df['prompt'] = movies_df.apply(generate_prompt, axis=1)

# Display the first few rows with the generated prompts
movies_df[['name', 'prompt']].head()

,name,prompt
0,The Shining,Tell me about the movie The Shining released i...
1,The Blue Lagoon,Tell me about the movie The Blue Lagoon releas...
2,Star Wars: Episode V - The Empire Strikes Back,Tell me about the movie Star Wars: Episode V -...
3,Airplane!,Tell me about the movie Airplane! released in ...
4,Caddyshack,Tell me about the movie Caddyshack released in...

In [28]:
# Create a DataFrame for the classification task with 'genre' as the target variable
classification_df = movies_df.copy()

# Generate prompts for classification, excluding the 'genre' from the prompt
classification_df['classification_prompt'] = classification_df.apply(
    lambda row: f"Tell me about the movie {row['name']} released in {row['year']}. It is directed by {row['director']} and stars {row['star']}, duration of movie is {row['runtime']} minutes. What is Genre of this movie?",
    axis=1
)

# Create a DataFrame for the regression task with 'gross' as the target variable
regression_df = movies_df.copy()

# Generate prompts for regression, excluding the 'gross' from the prompt
regression_df['regression_prompt'] = regression_df.apply(
    lambda row: f"Tell me about the movie {row['name']} released in {row['year']}. It is directed by {row['director']} and stars {row['star']}, duration of movie is {row['runtime']} minutes. Can you predict the score of the movie?",
    axis=1
)

# Select only relevant columns for classification and regression
classification_df = classification_df[['classification_prompt', 'genre']]
regression_df = regression_df[['regression_prompt', 'score']]

# Display the first few rows of each DataFrame
classification_df.head(), regression_df.head()

(                               classification_prompt      genre
 0  Tell me about the movie The Shining released i...      Drama
 1  Tell me about the movie The Blue Lagoon releas...  Adventure
 2  Tell me about the movie Star Wars: Episode V -...     Action
 3  Tell me about the movie Airplane! released in ...     Comedy
 4  Tell me about the movie Caddyshack released in...     Comedy,
                                    regression_prompt  score
 0  Tell me about the movie The Shining released i...    8.4
 1  Tell me about the movie The Blue Lagoon releas...    5.8
 2  Tell me about the movie Star Wars: Episode V -...    8.7
 3  Tell me about the movie Airplane! released in ...    7.7
 4  Tell me about the movie Caddyshack released in...    7.3)

In [29]:
# Save the classification and regression DataFrames to separate CSV files
classification_df.to_csv('classification.csv', index=False)
regression_df.to_csv('regression.csv', index=False)

In [17]:
import pickle

# Load the embeddings from the pickle file
with open('embeddings.pkl', 'rb') as f:
    embeddings = pickle.load(f)

# Print the loaded embeddings (optional)
print(len(embeddings[0]))
for i in range(50):
    print(embeddings[i])

# Check the number of embeddings loaded (optional)
# print(f"Loaded {len(embeddings)} embeddings from the pickle file.")

4096
[-2.96875   -4.59375    2.3125    ... -1.875      1.734375   0.8359375]
[-1.7421875 -5.1875     3.0625    ... -1.8203125  1.203125   0.71875  ]
[-0.64453125 -4.78125     3.234375   ... -0.48046875  1.109375
  0.546875  ]
[-2.421875  -5.3125     3.53125   ... -0.0625     1.609375   1.6015625]
[-1.3359375  -4.90625     2.15625    ...  0.09179688  1.484375
  1.6796875 ]
[-3.75       -4.40625     2.09375    ... -0.78125     1.4609375
 -0.13574219]
[-1.78125   -5.90625    2.453125  ...  0.140625   2.34375    0.7421875]
[-1.6484375 -4.71875    2.0625    ... -1.1171875  1.703125   1.703125 ]
[-0.8046875  -4.84375     1.828125   ...  2.46875     1.6171875
  0.43554688]
[-1.1484375  -4.90625     1.609375   ... -1.          1.5390625
  0.77734375]
[-1.5546875  -6.375       1.28125    ...  0.11767578  1.53125
  1.2890625 ]
[-2.390625   -4.5625      2.078125   ... -0.24707031  0.7734375
  1.859375  ]
[-0.54296875 -6.03125     3.40625    ...  0.0859375   1.40625
  0.69921875]
[-1.734375   -5.71875     3.203125   ...  0.20800781  1.578125
  0.08984375]
[-2.28125    -5.1875      2.0625     ... -0.12890625  1.6796875
  0.37890625]
[-1.6796875 -4.90625    3.53125   ... -0.3046875  0.546875  -0.5546875]
[-0.64453125 -5.28125     4.1875     ...  0.10839844 -1.125
  0.98828125]
[-0.8203125  -5.46875     3.0625     ... -0.10888672  0.35546875
  0.56640625]
[-3.375      -4.84375     3.         ... -1.796875    1.4609375
  0.44140625]
[-2.734375   -5.28125     2.21875    ...  0.8984375   1.375
  0.38867188]
[-2.671875  -6.03125    1.0703125 ... -0.296875   0.890625   0.8203125]
[-0.8828125 -5.8125     1.046875  ... -0.59375    1.3828125 -0.59375  ]
[-1.484375   -5.96875     2.515625   ... -0.03662109  1.6015625
 -0.47265625]
[-2.03125    -6.3125      4.03125    ...  0.18652344 -0.0859375
 -0.05810547]
[-0.21289062 -5.46875     1.46875    ...  0.88671875  1.015625
 -0.4296875 ]
[-3.46875    -4.625       2.53125    ... -0.95703125  0.5078125
  0.73828125]
[-1.8671875  -5.625       3.734375   ... -0.75390625  1.25
  0.703125  ]
[-1.6484375  -4.53125     2.921875   ... -1.421875    2.171875
 -0.42773438]
[-1.703125   -5.0625      2.15625    ...  0.0177002   0.89453125
  0.43164062]
[-2.171875   -5.75        1.7109375  ... -0.46875     0.58984375
  0.703125  ]
[-1.         -6.15625     2.4375     ...  0.09423828  1.0546875
  1.4921875 ]
[-2.90625    -5.28125     2.828125   ...  0.04248047  1.390625
  0.21289062]
[-1.6796875  -4.90625     2.125      ...  0.765625    0.9375
  0.79296875]
[-0.25       -5.75        1.5703125  ... -0.73046875  0.5859375
  1.5546875 ]
[-1.875      -5.84375     2.8125     ...  0.34765625  1.6015625
  1.3828125 ]
[-1.0234375  -5.5625      3.5625     ...  0.15039062  1.375
  1.4375    ]
[-1.796875   -5.71875     2.109375   ...  0.44140625  0.9453125
  1.6484375 ]
[-2.453125   -5.4375      0.97265625 ... -0.40820312  0.82421875
  0.08300781]
[-2.375      -5.8125      2.890625   ...  0.37304688  0.921875
  0.51171875]
[-1.0078125  -5.71875     4.90625    ...  0.21875     0.70703125
  1.5234375 ]
[-2.421875   -4.96875     4.25       ... -0.51953125  0.21386719
  1.421875  ]
[-1.8984375  -4.6875      2.28125    ... -0.5546875   0.33007812
  1.0546875 ]
[-2.40625   -5.09375    1.78125   ...  0.453125   1.6796875  0.921875 ]
[-2.         -5.4375      2.46875    ...  0.63671875  1.171875
  1.7421875 ]
[-1.8359375  -5.96875     2.421875   ... -1.125       1.2578125
  0.60546875]
[-2.515625  -4.875      2.125     ... -0.28125    0.4609375  1.859375 ]
[-1.8671875  -5.5625      1.8046875  ... -0.88671875  1.8046875
  1.5       ]
[-3.09375    -4.78125     3.203125   ... -0.58984375  1.3203125
  1.015625  ]
[-1.8046875 -5.4375     2.09375   ...  0.78125    1.2734375  1.9765625]
[-1.359375  -4.5625     2.1875    ... -0.6015625  0.3671875  1.5234375]

In [16]:
import pandas as pd

# Load the original movie dataset
file_path = 'movies.csv'
movies_df = pd.read_csv(file_path)

# Create a DataFrame for the regression task with 'runtime' as the target variable
regression_df = movies_df.copy()

# Generate prompts for regression, excluding the 'runtime' from the prompt
regression_df['regression_prompt'] = regression_df.apply(
    lambda row: f"Tell me about the movie {row['name']} released in {row['year']}. It is a {row['genre']} directed by {row['director']} and stars {row['star']}. What other notable aspects are there?",
    axis=1
)

# Select only relevant columns for regression
regression_df = regression_df[['regression_prompt', 'runtime']]

# Save the updated DataFrame to a CSV file
regression_df.to_csv('regression_prompts_runtime.csv', index=False)